blank_issues_enabled: false
contact_links:
  - name: IT Kamianets community
    url: https://itkamianets.com
    about: Visit the platform to learn more about the IT community of Kamianets-Podilskyi.
